### ISSUE TITLE
Android 14 APi 34 CANNOT INSTALL 

### ISSUE THREAD

**Issue by 01soni247** [enaix/Kirikiroid2-debloated#1]

**Comment by enaix** [comment]
Which version of the app cannot install? Please try Kirikiroid2-yuri apk, it should be patched

**Comment by enaix** [comment]
![IMAGE 2024-05-20 22:20:31](https://github.com/enaix/Kirikiroid2-debloated/assets/64410733/ba4cf699-2e59-49b2-8b4e-895cf9a84e52)

It works! That would be great if you could test the apk on your device and give feedback (you may find the new apk in releases)
